### ISSUE TITLE
With shadow build library is not found

### ISSUE THREAD

**Issue by kjelt** [FSund/qtcreator-project-structure#2]
I loaded project into qt creator and chose build all.

Here is the result:
```
20:27:36: Führe Schritte für Projekt MyProject aus...
20:27:36: Unveränderte Konfiguration, qmake-Schritt wird übersprungen.
20:27:36: Starte "D:\Qt\Qt5.7.0\Tools\mingw530_32\bin\mingw32-make.exe" 
cd src\ && ( if not exist Makefile D:\Qt\Qt5.7.0\5.7\mingw53_32\bin\qmake.exe D:\workspace\test_cmplx\src\src.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && D:/Qt/Qt5.7.0/Tools/mingw530_32/bin/mingw32-make -f Makefile 
mingw32-make[1]: Entering directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/src'
D:/Qt/Qt5.7.0/Tools/mingw530_32/bin/mingw32-make -f Makefile.Debug
mingw32-make[2]: Entering directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/src'
g++ -c -pipe -fno-keep-inline-dllexport -g -std=gnu++11 -frtti -Wall -Wextra -fexceptions -mthreads -DUNICODE -DQT_QML_DEBUG -I..\..\test_cmplx\src -I. -I..\..\test_cmplx\src -I..\..\..\Qt\Qt5.7.0\5.7\mingw53_32\mkspecs\win32-g++  -o debug\myclass.o ..\..\test_cmplx\src\myclass.cpp
g++ -shared -Wl,-subsystem,console -mthreads -Wl,--out-implib,debug\libmyapp.a -o debug\myapp.dll debug/myclass.o  
mingw32-make[2]: Leaving directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/src'
mingw32-make[1]: Leaving directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/src'
cd app\ && ( if not exist Makefile D:\Qt\Qt5.7.0\5.7\mingw53_32\bin\qmake.exe D:\workspace\test_cmplx\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && D:/Qt/Qt5.7.0/Tools/mingw530_32/bin/mingw32-make -f Makefile 
mingw32-make[1]: Entering directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/app'
D:/Qt/Qt5.7.0/Tools/mingw530_32/bin/mingw32-make -f Makefile.Debug
mingw32-make[2]: Entering directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/app'
g++ -c -pipe -fno-keep-inline-dllexport -g -std=gnu++11 -frtti -Wall -Wextra -fexceptions -mthreads -DUNICODE -DQT_QML_DEBUG -I..\..\test_cmplx\app -I. -I..\..\test_cmplx\src -I..\..\..\Qt\Qt5.7.0\5.7\mingw53_32\mkspecs\win32-g++  -o debug\main.o ..\..\test_cmplx\app\main.cpp
g++ -Wl,-subsystem,console -mthreads -o debug\app.exe debug/main.o  -L..\src -lmyapp 
D:/Qt/Qt5.7.0/Tools/mingw530_32/bin/../lib/gcc/i686-w64-mingw32/5.3.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find -lmyapp
collect2.exe: error: ld returned 1 exit status
Makefile.Debug:61: recipe for target 'debug\app.exe' failed
mingw32-make[2]: Leaving directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/app'
mingw32-make[2]: *** [debug\app.exe] Error 1
Makefile:34: recipe for target 'debug' failed
mingw32-make[1]: Leaving directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/app'
mingw32-make[1]: *** [debug] Error 2
Makefile:83: recipe for target 'sub-app-make_first-ordered' failed
mingw32-make: *** [sub-app-make_first-ordered] Error 2
20:27:42: Der Prozess "D:\Qt\Qt5.7.0\Tools\mingw530_32\bin\mingw32-make.exe" wurde mit dem Rückgabewert 2 beendet.
Fehler beim Erstellen/Deployment des Projekts MyProject (Kit: Desktop Qt 5.7.0 MinGW 32bit)
Bei der Ausführung von Schritt "Make"
20:27:42: Verstrichene Zeit: 00:06.
```

**Comment by FSund** [comment]
I'm not sure what the issue is. It compiles fine for me in QtCreator 4.2.1. I'm on Linux though, it seems like you are using Windows and MinGW?

Seems like you get an error `cannot find -lmyapp` when making the executable.
Are you sure your build system is set up correct?

This is my compile output:

```
08:12:33: Running steps for project MyProject...
08:12:33: Starting: "/usr/lib/x86_64-linux-gnu/qt5/bin/qmake" /home/filip/tmp/qtcreator-project-structure/MyProject.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug
08:12:33: The process "/usr/lib/x86_64-linux-gnu/qt5/bin/qmake" exited normally.
08:12:33: Starting: "/usr/bin/make" qmake_all
cd src/ && /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/filip/tmp/qtcreator-project-structure/src/src.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile
cd src/ && /usr/bin/make -f Makefile qmake_all
make[1]: Entering directory `/home/filip/tmp/build-MyProject-Desktop-Debug/src'
make[1]: Nothing to be done for `qmake_all'.
make[1]: Leaving directory `/home/filip/tmp/build-MyProject-Desktop-Debug/src'
cd app/ && /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/filip/tmp/qtcreator-project-structure/app/app.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile
cd app/ && /usr/bin/make -f Makefile qmake_all
make[1]: Entering directory `/home/filip/tmp/build-MyProject-Desktop-Debug/app'
make[1]: Nothing to be done for `qmake_all'.
make[1]: Leaving directory `/home/filip/tmp/build-MyProject-Desktop-Debug/app'
cd tests/ && /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/filip/tmp/qtcreator-project-structure/tests/tests.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile
cd tests/ && /usr/bin/make -f Makefile qmake_all
make[1]: Entering directory `/home/filip/tmp/build-MyProject-Desktop-Debug/tests'
make[1]: Nothing to be done for `qmake_all'.
make[1]: Leaving directory `/home/filip/tmp/build-MyProject-Desktop-Debug/tests'
08:12:33: The process "/usr/bin/make" exited normally.
08:12:33: Starting: "/usr/bin/make" 
cd src/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/filip/tmp/qtcreator-project-structure/src/src.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && /usr/bin/make -f Makefile 
make[1]: Entering directory `/home/filip/tmp/build-MyProject-Desktop-Debug/src'
g++ -c -m64 -pipe -g -Wall -W -fPIC -DQT_QML_DEBUG -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I../../qtcreator-project-structure/src -I../../qtcreator-project-structure/src -I. -o myclass.o ../../qtcreator-project-structure/src/myclass.cpp
rm -f libmyapp.so.1.0.0 libmyapp.so libmyapp.so.1 libmyapp.so.1.0
g++ -m64 -shared -Wl,-soname,libmyapp.so.1 -o libmyapp.so.1.0.0 myclass.o    
ln -s libmyapp.so.1.0.0 libmyapp.so
ln -s libmyapp.so.1.0.0 libmyapp.so.1
ln -s libmyapp.so.1.0.0 libmyapp.so.1.0
{ test -z "" || cd ""; } && test $(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index ." -ex quit 'libmyapp.so.1.0.0' && test -f libmyapp.so.1.0.0.gdb-index && objcopy --add-section '.gdb_index=libmyapp.so.1.0.0.gdb-index' --set-section-flags '.gdb_index=readonly' 'libmyapp.so.1.0.0' 'libmyapp.so.1.0.0' && rm -f libmyapp.so.1.0.0.gdb-index || true
make[1]: Leaving directory `/home/filip/tmp/build-MyProject-Desktop-Debug/src'
cd app/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/filip/tmp/qtcreator-project-structure/app/app.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && /usr/bin/make -f Makefile 
make[1]: Entering directory `/home/filip/tmp/build-MyProject-Desktop-Debug/app'
g++ -c -m64 -pipe -g -Wall -W -fPIE -DQT_QML_DEBUG -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I../../qtcreator-project-structure/app -I../../qtcreator-project-structure/src -I. -o main.o ../../qtcreator-project-structure/app/main.cpp
g++ -m64 -o app main.o   -L../src -lmyapp 
{ test -n "" && DESTDIR="" || DESTDIR=.; } && test $(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $DESTDIR" -ex quit 'app' && test -f app.gdb-index && objcopy --add-section '.gdb_index=app.gdb-index' --set-section-flags '.gdb_index=readonly' 'app' 'app' && rm -f app.gdb-index || true
make[1]: Leaving directory `/home/filip/tmp/build-MyProject-Desktop-Debug/app'
cd tests/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/filip/tmp/qtcreator-project-structure/tests/tests.pro -spec linux-g++-64 CONFIG+=debug CONFIG+=qml_debug -o Makefile ) && /usr/bin/make -f Makefile 
make[1]: Entering directory `/home/filip/tmp/build-MyProject-Desktop-Debug/tests'
g++ -c -m64 -pipe -g -Wall -W -fPIE -DQT_QML_DEBUG -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I../../qtcreator-project-structure/tests -I../../qtcreator-project-structure/src -I. -o main.o ../../qtcreator-project-structure/tests/main.cpp
g++ -m64 -o tests main.o   -lunittest++ -L../src -lmyapp 
{ test -n "" && DESTDIR="" || DESTDIR=.; } && test $(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $DESTDIR" -ex quit 'tests' && test -f tests.gdb-index && objcopy --add-section '.gdb_index=tests.gdb-index' --set-section-flags '.gdb_index=readonly' 'tests' 'tests' && rm -f tests.gdb-index || true
make[1]: Leaving directory `/home/filip/tmp/build-MyProject-Desktop-Debug/tests'
08:12:34: The process "/usr/bin/make" exited normally.
08:12:34: Elapsed time: 00:01.
```

**Comment by kjelt** [comment]
I have changed nothing before compiling. All values should be default in my opinion.

I think the linker is not able to find the library due to the debug/release subfolders.

Attached the build folder
[build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug.gz](https://github.com/FSund/qtcreator-project-structure/files/872880/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug.gz)

Win (Vista) and MinGW is right and Qt Creator 4.0.2 .

**Comment by FSund** [comment]
It seems like your debug/release folders are in the wrong order. In the attached build folder you have debug and release folders inside both the app, src and tests folders. My build system is set up so I get the following structure

```
tmp
/qtcreator-project-structure (this just contains all the files from the git repo)
    /app
        ...
    /src
        ...
    /tests
        ...
/build-MyProject-Desktop-Debug
    /app
        /app (executable)
        /main.o
        /Makefile
    /src
        /libmyapp.so
        /libmyapp.so.1
        /libmyapp.so.1.0
        /libmyapp.so.1.0.0
        /Makefile
        /myclass.o
    /tests
        /main.o
        /Makefile
        /tests (executable)
```

Your compilation is failing because the linker cannot fint `-lmyapp`, so I think your include paths must be set up wrong.

When compiling you first enter the folder
`D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/app`
and then try to compile app.exe using
`g++ -Wl,-subsystem,console -mthreads -o debug\app.exe debug/main.o  -L..\src -lmyapp `.
You include the folder `..\src` using `-L..\src` and try to link `-lmyapp`, but `myapp.a` and `myapp.dll` are actually here:
`D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/src/debug/libmyapp.a`
`D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/src/debug/myapp.dll`

**Comment by kjelt** [comment]
I think this is it: 
http://stackoverflow.com/questions/1298988/qt-does-not-create-output-files-in-debug-release-folders-in-linux/4563512#4563512

so i added in default.pri this line:
`win32:CONFIG -= debug_and_release debug_and_release_target`

now the debug and release subfolders are gone. 
Strange those values are set on Windows as default and not on Linux.

Building gives:
13:45:53: Führe Schritte für Projekt MyProject aus...
13:45:53: Starte "D:\Qt\Qt5.7.0\Tools\mingw530_32\bin\mingw32-make.exe" clean
cd src\ && ( if not exist Makefile D:\Qt\Qt5.7.0\5.7\mingw53_32\bin\qmake.exe D:\workspace\test_cmplx\src\src.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && D:/Qt/Qt5.7.0/Tools/mingw530_32/bin/mingw32-make -f Makefile clean
mingw32-make[1]: Entering directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/src'
D:\Qt\Qt5.7.0\5.7\mingw53_32\bin\qmake.exe -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ..\..\test_cmplx\src\src.pro
del myclass.o
del libmyapp.a
mingw32-make[1]: Leaving directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/src'
cd app\ && ( if not exist Makefile D:\Qt\Qt5.7.0\5.7\mingw53_32\bin\qmake.exe D:\workspace\test_cmplx\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && D:/Qt/Qt5.7.0/Tools/mingw530_32/bin/mingw32-make -f Makefile clean
mingw32-make[1]: Entering directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/app'
D:\Qt\Qt5.7.0\5.7\mingw53_32\bin\qmake.exe -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ..\..\test_cmplx\app\app.pro
del main.o
mingw32-make[1]: Leaving directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/app'
cd tests\ && ( if not exist Makefile D:\Qt\Qt5.7.0\5.7\mingw53_32\bin\qmake.exe D:\workspace\test_cmplx\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && D:/Qt/Qt5.7.0/Tools/mingw530_32/bin/mingw32-make -f Makefile clean
mingw32-make[1]: Entering directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/tests'
D:\Qt\Qt5.7.0\5.7\mingw53_32\bin\qmake.exe -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ..\..\test_cmplx\tests\tests.pro
del main.o
mingw32-make[1]: Leaving directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/tests'
13:46:03: Der Prozess "D:\Qt\Qt5.7.0\Tools\mingw530_32\bin\mingw32-make.exe" wurde normal beendet.
13:46:03: Unveränderte Konfiguration, qmake-Schritt wird übersprungen.
13:46:03: Starte "D:\Qt\Qt5.7.0\Tools\mingw530_32\bin\mingw32-make.exe" 
cd src\ && ( if not exist Makefile D:\Qt\Qt5.7.0\5.7\mingw53_32\bin\qmake.exe D:\workspace\test_cmplx\src\src.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && D:/Qt/Qt5.7.0/Tools/mingw530_32/bin/mingw32-make -f Makefile 
mingw32-make[1]: Entering directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/src'
g++ -c -pipe -fno-keep-inline-dllexport -g -std=gnu++11 -frtti -Wall -Wextra -fexceptions -mthreads -DUNICODE -DQT_QML_DEBUG -I..\..\test_cmplx\src -I. -I..\..\test_cmplx\src -I..\..\..\Qt\Qt5.7.0\5.7\mingw53_32\mkspecs\win32-g++  -o myclass.o ..\..\test_cmplx\src\myclass.cpp
g++ -shared -Wl,-subsystem,console -mthreads -Wl,--out-implib,libmyapp.a -o myapp.dll myclass.o  
mingw32-make[1]: Leaving directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/src'
cd app\ && ( if not exist Makefile D:\Qt\Qt5.7.0\5.7\mingw53_32\bin\qmake.exe D:\workspace\test_cmplx\app\app.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && D:/Qt/Qt5.7.0/Tools/mingw530_32/bin/mingw32-make -f Makefile 
mingw32-make[1]: Entering directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/app'
g++ -c -pipe -fno-keep-inline-dllexport -g -std=gnu++11 -frtti -Wall -Wextra -fexceptions -mthreads -DUNICODE -DQT_QML_DEBUG -I..\..\test_cmplx\app -I. -I..\..\test_cmplx\src -I..\..\..\Qt\Qt5.7.0\5.7\mingw53_32\mkspecs\win32-g++  -o main.o ..\..\test_cmplx\app\main.cpp
g++ -Wl,-subsystem,console -mthreads -o app.exe main.o  -L..\src -lmyapp 
mingw32-make[1]: Leaving directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/app'
cd tests\ && ( if not exist Makefile D:\Qt\Qt5.7.0\5.7\mingw53_32\bin\qmake.exe D:\workspace\test_cmplx\tests\tests.pro -spec win32-g++ "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && D:/Qt/Qt5.7.0/Tools/mingw530_32/bin/mingw32-make -f Makefile 
mingw32-make[1]: Entering directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/tests'
g++ -c -pipe -fno-keep-inline-dllexport -g -std=gnu++1y -frtti -Wall -Wextra -fexceptions -mthreads -DUNICODE -DQT_QML_DEBUG -I..\..\test_cmplx\tests -I. -I..\..\test_cmplx\src -I..\..\..\Qt\Qt5.7.0\5.7\mingw53_32\mkspecs\win32-g++  -o main.o ..\..\test_cmplx\tests\main.cpp
g++ -Wl,-subsystem,console -mthreads -o tests.exe main.o  -L..\src -lmyapp 
mingw32-make[1]: Leaving directory 'D:/workspace/build-MyProject-Desktop_Qt_5_7_0_MinGW_32bit-Debug/tests'
13:46:27: Der Prozess "D:\Qt\Qt5.7.0\Tools\mingw530_32\bin\mingw32-make.exe" wurde normal beendet.
13:46:27: Verstrichene Zeit: 00:34.

Thanks for your help with this issue.

**Comment by FSund** [comment]
That's a very odd difference between Linux and Windows. I've always used QtCreator on Linux, that's why I've never encountered this issue.

Glad you were able to figure it out!
